"""Release-facing validation for the Mobius plugin bundle."""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
PLUGIN_ROOT = REPO_ROOT / "plugins" / "mobius"


def rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def read_json(path: Path) -> dict[str, object]:
    data = json.loads(path.read_text(encoding="utf-8"))
    assert isinstance(data, dict), f"{rel(path)} must contain a JSON object"
    return data


def release_text_paths() -> list[Path]:
    excluded_parts = {".git", ".mobius", ".venv", "__pycache__"}
    paths: list[Path] = []
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel_parts = path.relative_to(REPO_ROOT).parts
        if any(part in excluded_parts for part in rel_parts):
            continue
        try:
            path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        paths.append(path)
    return paths


def test_plugin_source_tree_has_no_generated_runtime_artifacts() -> None:
    generated_dirs = [
        path
        for path in PLUGIN_ROOT.rglob("*")
        if path.is_dir() and path.name in {".venv", "__pycache__"}
    ]
    generated_files = [path for path in PLUGIN_ROOT.rglob("*.pyc") if path.is_file()]

    assert not generated_dirs, "generated runtime directories are present: " + ", ".join(
        rel(path) for path in generated_dirs
    )
    assert not generated_files, "generated bytecode files are present: " + ", ".join(
        rel(path) for path in generated_files
    )


def test_required_plugin_bundle_files_exist() -> None:
    required_paths = [
        ".codex-plugin/plugin.json",
        ".mcp.json",
        "hooks/hooks.json",
        "skills/mobius-plan/SKILL.md",
        "skills/mobius-loop/SKILL.md",
        "skills/mobius-plan/agents/openai.yaml",
        "skills/mobius-loop/agents/openai.yaml",
        "scripts/mobius.py",
        "scripts/mobius_cv_mcp.py",
        "scripts/mobius_cv_mcp_server.sh",
        "scripts/mobius_hook_launcher.sh",
        "pyproject.toml",
        "uv.lock",
        "references/data-contracts.md",
        "references/mobiuscv-mcp.md",
        "references/hooks.md",
    ]
    missing = [path for path in required_paths if not (PLUGIN_ROOT / path).is_file()]
    assert missing == []


def test_development_only_files_are_not_in_plugin_bundle() -> None:
    forbidden_plugin_source_paths = [
        "scripts/" + "verify.sh",
        "scripts/mobius_regression_tests.py",
        "tests/mobius_regression_tests.py",
        "tests/test_release_bundle.py",
        "requirements-dev.txt",
    ]
    present = [path for path in forbidden_plugin_source_paths if (PLUGIN_ROOT / path).exists()]
    assert present == []


def test_plugin_manifest_marketplace_mcp_and_hooks_shape() -> None:
    expected_owner = "boman-ng"
    expected_slug = f"{expected_owner}/mobius"
    expected_repo_url = f"https://github.com/{expected_slug}"

    manifest = read_json(PLUGIN_ROOT / ".codex-plugin/plugin.json")
    assert manifest.get("name") == "mobius"
    assert manifest.get("version") == "0.3.0"
    assert manifest.get("license") == "Apache-2.0"
    assert manifest.get("skills") == "./skills/"
    assert manifest.get("mcpServers") == "./.mcp.json"
    assert manifest.get("repository") == expected_repo_url
    assert manifest.get("homepage") == f"{expected_repo_url}#readme"
    author = manifest.get("author")
    assert isinstance(author, dict)
    assert author.get("url") == f"https://github.com/{expected_owner}"
    interface = manifest.get("interface")
    assert isinstance(interface, dict)
    assert interface.get("displayName") == "Mobius"
    assert interface.get("websiteURL") == expected_repo_url

    mcp = read_json(PLUGIN_ROOT / ".mcp.json")
    mcp_servers = mcp.get("mcpServers")
    assert isinstance(mcp_servers, dict)
    server = mcp_servers.get("mobius-cv")
    assert isinstance(server, dict)
    assert server.get("cwd") == "."
    assert server.get("command") == "/bin/bash"
    assert server.get("args") == ["./scripts/mobius_cv_mcp_server.sh"]

    hooks = read_json(PLUGIN_ROOT / "hooks/hooks.json").get("hooks")
    assert isinstance(hooks, dict)
    for event in ("PreToolUse", "Stop"):
        entries = hooks.get(event)
        assert isinstance(entries, list) and entries
        assert "mobius_hook_launcher.sh" in json.dumps(entries)

    marketplace = read_json(REPO_ROOT / ".agents/plugins/marketplace.json")
    plugins = marketplace.get("plugins")
    assert marketplace.get("name") == "mobius"
    assert isinstance(plugins, list)
    entry = next(
        (
            item
            for item in plugins
            if isinstance(item, dict) and item.get("name") == "mobius"
        ),
        None,
    )
    assert isinstance(entry, dict)
    source = entry.get("source")
    assert isinstance(source, dict)
    assert source.get("path") == "./plugins/mobius"
    policy = entry.get("policy")
    assert isinstance(policy, dict)
    assert policy.get("installation") == "AVAILABLE"
    assert policy.get("authentication") == "ON_INSTALL"


def test_release_text_has_no_forbidden_local_or_stale_tokens() -> None:
    expected_owner = "boman-ng"
    expected_slug = f"{expected_owner}/mobius"
    linux_home_prefix = "/" + "home" + "/"
    mac_home_prefix = "/" + "Users" + "/"
    win_home_prefix = "C:" + "\\" + "Users" + "\\"
    personal_path_patterns = [
        (re.compile(re.escape(linux_home_prefix) + r"[A-Za-z0-9_.-]+"), "Linux home path"),
        (re.compile(re.escape(mac_home_prefix) + r"[A-Za-z0-9_.-]+"), "macOS home path"),
        (re.compile(re.escape(win_home_prefix) + r"[A-Za-z0-9_.-]+"), "Windows home path"),
    ]

    stale_owner = "wu" + "bw"
    codex_skills = ".codex/" + "skills"
    forbidden_tokens = [
        f"github.com/{stale_owner}",
        f"{stale_owner}/mobius",
        linux_home_prefix + stale_owner,
        ".codex/plugins/cache/" + "personal",
        "0.1.0+" + "codex",
        "~/" + codex_skills,
        "$HOME/" + codex_skills,
        "${HOME}/" + codex_skills,
        "bash scripts/" + "verify.sh",
        "scripts/" + "verify.sh",
    ]
    marketplace_add = "codex plugin " + "marketplace add "

    for path in release_text_paths():
        text = path.read_text(encoding="utf-8")
        path_rel = rel(path)
        for forbidden in forbidden_tokens:
            assert forbidden not in text, f"{path_rel} contains forbidden token {forbidden}"
        for pattern, label in personal_path_patterns:
            assert pattern.search(text) is None, f"{path_rel} contains a hardcoded {label}"
        for match in re.finditer(re.escape(marketplace_add) + r"([^\s]+)", text):
            target = match.group(1)
            assert target.startswith("/") or target == expected_slug, (
                f"{path_rel} contains unexpected marketplace coordinate {target}"
            )
        for match in re.finditer(
            r"https://github\.com/([A-Za-z0-9_.-]+)(?:/([A-Za-z0-9_.-]+))?",
            text,
        ):
            owner = match.group(1)
            repo_name = match.group(2)
            assert owner == expected_owner and (repo_name is None or repo_name == "mobius"), (
                f"{path_rel} contains unexpected GitHub URL owner or repository"
            )


def test_git_hygiene_for_release_state() -> None:
    subprocess.run(["git", "-C", str(REPO_ROOT), "diff", "--check"], check=True)
    status = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "status", "--short", "--ignored=no"],
        text=True,
        capture_output=True,
        check=True,
    ).stdout
    assert not re.search(r"^[ MADRCU?!]{2} [.]mobius($|/)", status, re.MULTILINE)
    subprocess.run(["git", "-C", str(REPO_ROOT), "check-ignore", "-q", ".mobius/probe"], check=True)


def test_ci_workflow_uses_direct_python_checks_not_verify_shell() -> None:
    workflow = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    assert "python -m pytest" in workflow
    assert "python -m py_compile" in workflow
    assert "hook-health" in workflow
    assert "git diff --check" in workflow
    assert "git check-ignore -q .mobius/probe" in workflow
    assert "PYTHONDONTWRITEBYTECODE" in workflow
    assert "PYTHONPYCACHEPREFIX" in workflow
    assert "scripts/" + "verify.sh" not in workflow
