#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN_ROOT="$REPO_ROOT/plugins/mobius"
TEMP_DIRS=()

cleanup() {
  local dir
  for dir in "${TEMP_DIRS[@]}"; do
    rm -rf "$dir"
  done
}
trap cleanup EXIT

fail() {
  echo "mobius verify failed: $*" >&2
  exit 1
}

check_clean() {
  local dirty=0
  if find "$PLUGIN_ROOT" -type d \( -name .venv -o -name __pycache__ \) -print | grep -q .; then
    echo "mobius verify failed: generated runtime directories are present" >&2
    dirty=1
  fi
  if find "$PLUGIN_ROOT" -type f -name '*.pyc' -print | grep -q .; then
    echo "mobius verify failed: generated bytecode files are present" >&2
    dirty=1
  fi
  return "$dirty"
}

validate_bundle() {
  python3 - "$REPO_ROOT" "$PLUGIN_ROOT" <<'PY'
import json
import re
import sys
from pathlib import Path

repo = Path(sys.argv[1])
plugin = Path(sys.argv[2])
expected_owner = "boman-ngs"
expected_slug = f"{expected_owner}/mobius"
expected_author_url = f"https://github.com/{expected_owner}"
expected_repo_url = f"https://github.com/{expected_slug}"
linux_home_prefix = "/" + "home" + "/"
mac_home_prefix = "/" + "Users" + "/"
win_home_prefix = "C:" + "\\" + "Users" + "\\"
personal_path_patterns = [
    (re.compile(re.escape(linux_home_prefix) + r"[A-Za-z0-9_.-]+"), "Linux home path"),
    (re.compile(re.escape(mac_home_prefix) + r"[A-Za-z0-9_.-]+"), "macOS home path"),
    (re.compile(re.escape(win_home_prefix) + r"[A-Za-z0-9_.-]+"), "Windows home path"),
]


def fail(message: str) -> None:
    raise SystemExit(f"mobius verify failed: {message}")


def read_json(path: Path) -> dict:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"missing {path.relative_to(repo)}")
    except json.JSONDecodeError as exc:
        fail(f"{path.relative_to(repo)} is invalid JSON: {exc.msg}")
    if not isinstance(data, dict):
        fail(f"{path.relative_to(repo)} must contain a JSON object")
    return data


required_paths = [
    ".codex-plugin/plugin.json",
    ".mcp.json",
    "hooks/hooks.json",
    "skills/mobius-plan/SKILL.md",
    "skills/mobius-loop/SKILL.md",
    "scripts/mobius.py",
    "scripts/mobius_cv_mcp.py",
    "scripts/mobius_cv_mcp_server.sh",
    "scripts/mobius_hook_launcher.sh",
    "pyproject.toml",
    "uv.lock",
    "references/mobiuscv-mcp.md",
    "references/hooks.md",
]
for rel in required_paths:
    if not (plugin / rel).is_file():
        fail(f"missing plugin file plugins/mobius/{rel}")

forbidden_plugin_source_paths = [
    "scripts/verify.sh",
    "scripts/mobius_regression_tests.py",
    "tests/mobius_regression_tests.py",
]
for rel in forbidden_plugin_source_paths:
    if (plugin / rel).exists():
        fail(f"development-only file must not be in plugin bundle: plugins/mobius/{rel}")

manifest = read_json(plugin / ".codex-plugin/plugin.json")
expected_manifest = {
    "name": "mobius",
    "version": "0.1.0",
    "license": "Apache-2.0",
    "skills": "./skills/",
    "mcpServers": "./.mcp.json",
}
for key, expected in expected_manifest.items():
    if manifest.get(key) != expected:
        fail(f"plugin.json {key!r} expected {expected!r}, got {manifest.get(key)!r}")
for key in ("homepage", "repository", "author", "interface"):
    if key not in manifest:
        fail(f"plugin.json missing {key}")
if manifest.get("repository") != expected_repo_url:
    fail(f"plugin.json repository must be {expected_repo_url}")
if manifest.get("homepage") != f"{expected_repo_url}#readme":
    fail(f"plugin.json homepage must be {expected_repo_url}#readme")
author = manifest.get("author")
if not isinstance(author, dict) or author.get("url") != expected_author_url:
    fail(f"plugin.json author.url must be {expected_author_url}")
interface = manifest.get("interface")
if not isinstance(interface, dict) or interface.get("displayName") != "Mobius":
    fail("plugin.json interface.displayName must be Mobius")
if interface.get("websiteURL") != expected_repo_url:
    fail(f"plugin.json interface.websiteURL must be {expected_repo_url}")

release_text_paths = []
excluded_parts = {".git", ".mobius", ".venv", "__pycache__"}
for path in repo.rglob("*"):
    if not path.is_file():
        continue
    rel_parts = path.relative_to(repo).parts
    if any(part in excluded_parts for part in rel_parts):
        continue
    try:
        path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        continue
    release_text_paths.append(path)

for path in release_text_paths:
    text = path.read_text(encoding="utf-8")
    rel = path.relative_to(repo)
    stale_owner = "wu" + "bw"
    codex_skills = ".codex/" + "skills"
    for forbidden in (
        f"github.com/{stale_owner}",
        f"{stale_owner}/mobius",
        linux_home_prefix + stale_owner,
        ".codex/plugins/cache/" + "personal",
        "0.1.0+" + "codex",
        "~/" + codex_skills,
        "$HOME/" + codex_skills,
        "${HOME}/" + codex_skills,
    ):
        if forbidden in text:
            fail(f"{rel} contains forbidden release-source token {forbidden}")
    for pattern, label in personal_path_patterns:
        if pattern.search(text):
            fail(f"{rel} contains a hardcoded {label}")
    marketplace_add = "codex plugin " + "marketplace add "
    for match in re.finditer(re.escape(marketplace_add) + r"([^\s]+)", text):
        target = match.group(1)
        if not target.startswith("/") and target != expected_slug:
            fail(f"{rel} contains unexpected marketplace coordinate {target}")
    for match in re.finditer(r"https://github\.com/([A-Za-z0-9_.-]+)(?:/([A-Za-z0-9_.-]+))?", text):
        owner = match.group(1)
        repo_name = match.group(2)
        if owner != expected_owner or (repo_name is not None and repo_name != "mobius"):
            fail(f"{rel} contains unexpected GitHub URL owner or repository")

mcp = read_json(plugin / ".mcp.json")
server = mcp.get("mcpServers", {}).get("mobius-cv")
if not isinstance(server, dict):
    fail(".mcp.json missing mcpServers.mobius-cv")
if server.get("cwd") != ".":
    fail(".mcp.json mobius-cv cwd must be .")
if server.get("args", [None])[0] != "./scripts/mobius_cv_mcp_server.sh":
    fail(".mcp.json mobius-cv must launch ./scripts/mobius_cv_mcp_server.sh")

hooks = read_json(plugin / "hooks/hooks.json").get("hooks")
if not isinstance(hooks, dict):
    fail("hooks/hooks.json missing hooks object")
for event in ("PreToolUse", "Stop"):
    entries = hooks.get(event)
    if not isinstance(entries, list) or not entries:
        fail(f"hooks/hooks.json missing {event} hook entries")
    serialized = json.dumps(entries)
    if "mobius_hook_launcher.sh" not in serialized:
        fail(f"{event} hooks must launch mobius_hook_launcher.sh")

marketplace = read_json(repo / ".agents/plugins/marketplace.json")
plugins = marketplace.get("plugins")
if marketplace.get("name") != "mobius" or not isinstance(plugins, list):
    fail("marketplace must define the mobius marketplace with a plugins array")
entry = next((item for item in plugins if isinstance(item, dict) and item.get("name") == "mobius"), None)
if entry is None:
    fail("marketplace missing mobius plugin entry")
if entry.get("source", {}).get("path") != "./plugins/mobius":
    fail("marketplace mobius source.path must be ./plugins/mobius")
policy = entry.get("policy", {})
if policy.get("installation") != "AVAILABLE" or policy.get("authentication") != "ON_INSTALL":
    fail("marketplace mobius policy must be AVAILABLE and ON_INSTALL")
PY
}

check_git_state() {
  if ! git -C "$REPO_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    return
  fi

  git -C "$REPO_ROOT" diff --check

  local status
  status="$(git -C "$REPO_ROOT" status --short --ignored=no)"
  if printf '%s\n' "$status" | grep -Eq '^[ MADRCU?!]{2} [.]mobius($|/)'; then
    fail "local Mobius state is visible to git status --ignored=no"
  fi

  if ! git -C "$REPO_ROOT" check-ignore -q .mobius; then
    fail ".mobius is not ignored by git"
  fi
}

check_clean

PYCACHE_ROOT="$(mktemp -d)"
TEMP_DIRS+=("$PYCACHE_ROOT")

PYTHONPYCACHEPREFIX="$PYCACHE_ROOT" python3 -m py_compile \
  "$PLUGIN_ROOT/scripts/mobius.py" \
  "$PLUGIN_ROOT/scripts/mobius_cv_mcp.py" \
  "$REPO_ROOT/tests/mobius_regression_tests.py"

PYTHONDONTWRITEBYTECODE=1 python3 "$REPO_ROOT/tests/mobius_regression_tests.py"

validate_bundle

if [[ -z "${PLUGIN_DATA:-}" ]]; then
  PLUGIN_DATA="$(mktemp -d)"
  export PLUGIN_DATA
  TEMP_DIRS+=("$PLUGIN_DATA")
fi

"$PLUGIN_ROOT/scripts/mobius_cv_mcp_server.sh" --self-check
PYTHONDONTWRITEBYTECODE=1 python3 "$PLUGIN_ROOT/scripts/mobius.py" --project-root "$REPO_ROOT" hook-health >/dev/null
check_git_state
check_clean
